version: '3.4'

services:
  nodepm2:
    image: nodepm2raccoon
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4500:4500
    volumes:
      - .:/usr/src/app
